### ISSUE TITLE
names_prefered counts of 0

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/go-whosonfirst-spelunker-httpd#17]
The names_prefered counts value of records always seems to be 0, example record: https://spelunker.whosonfirst.org/id/85633345/

There are preferred name properties in this record.. my guess is this has to do with preferred v prefered.

**Comment by thisisaaronland** [comment]
Yes, this is a bug here: https://github.com/whosonfirst/go-whosonfirst-spelunker/blob/main/document/names.go#L20

We're already due for a re-indexing because of issue #7 so we'll just add this to the queue.

**Comment by straup** [comment]
Fixed with re-indexing (and changes to `whosonfirst/go-whosonfirst-spelunker`).
