### ISSUE TITLE
Always allow Write Field editor in sidebar

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/go-whosonfirst-spelunker-httpd#43]
When loading a record that has been deprecated, the new Spelunker GUI removes the ability to edit the feature in Write Field. 

Which is probably a good thing (tm), but then there's this place: https://spelunker.whosonfirst.org/id/1292942521 which didn't get it's mz:is_current set correctly to 0 along the way.

I can edit it manually... but maybe we always allow editing?

If we do allow editing, then Write Field probably needs to also add a `CAUTION: Depreciated place` banner warning at the top (like the Spelunker has).

**Comment by thisisaaronland** [comment]
This is happening client-side in the JS here:

https://github.com/whosonfirst/go-whosonfirst-spelunker-httpd/blob/main/static/javascript/whosonfirst.spelunker.id.init.js#L271
