### ISSUE TITLE
Display of mz:is_ceased always shows as 1 instead of reflecting actual data value

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/go-whosonfirst-spelunker-httpd#7]
While viewing [Faymont](https://spelunker.whosonfirst.org/id/1360685533) neighbourhood in France. I observed that the `mz:is_ceased` is always set to **1**, even though nonsensically the `mz:is_current` property is still **1**, and there is no `edtf:*` details indicating the place is actually ceased. Browsing around it seems like this property is displaying on many records, including the country of [France](https://spelunker.whosonfirst.org/id/85633147).

<img width="684" alt="image" src="https://github.com/whosonfirst/go-whosonfirst-spelunker-httpd/assets/853051/9510c778-b041-4fb4-abe4-319560cc4f55">

Reviewing the [src GeoJSON data](https://github.com/whosonfirst-data/whosonfirst-data-admin-fr/blob/master/data/136/068/553/3/1360685533.geojson) and it seems like this property isn't present in the data for Faymont. 

Why is this property being added? Should it be added? The counts are useful at the top of the new page, but I'm not sure about mixing in calculated properties and data properties in the main body of the page... or we need an indicator (like a background color?) to alert in these situations?

Is `mz:is_is_ceased` being imputed during page render? If so there's a bug in how it's being calculated.

**Comment by thisisaaronland** [comment]
This is technically a bug in that the code here _should_ also be checking for `edtf.UNKNOWN_2012`. On the other hand we _should_ also update all those pre-2019 EDTF strings in all the WOF records.

https://github.com/whosonfirst/go-whosonfirst-spelunker/blob/main/document/existential.go#L31-L35
https://github.com/sfomuseum/go-edtf/blob/main/edtf.go#L16C7-L16C19

Either way, this will require re-indexing things (which will at least be a good "wax on, wax off" exercise). Leaving this issue open until this is completed:

https://github.com/whosonfirst/go-whosonfirst-spelunker/issues/2

**Comment by thisisaaronland** [comment]
One short-term solution would be to trap and remove `mz:is_*` properties here (until the re-indexing is complete):

https://github.com/whosonfirst/go-whosonfirst-spelunker-httpd/blob/main/static/javascript/whosonfirst.spelunker.properties.js

**Comment by straup** [comment]
* https://github.com/whosonfirst/go-whosonfirst-opensearch/releases/tag/v0.0.15
* https://github.com/whosonfirst/go-whosonfirst-spelunker/releases/tag/v0.0.1

**Comment by nvkelso** [comment]
Nice! I think I'm awaiting a deploy to verify fix... No hurry.

**Comment by thisisaaronland** [comment]
The issue has not been fixed. These are just steps along the way. The _real_ fix is going to be updating all the WOF records with bunk EDTF values:

* https://github.com/whosonfirst/go-whosonfirst-edtf?tab=readme-ov-file#update-open-unknown

**Comment by nvkelso** [comment]
@stepps00 FYI this implicates https://github.com/whosonfirst-data/whosonfirst-data/issues/1914 and crawling all the repos and updating EDTF values.

**Comment by straup** [comment]
Fixed with re-indexing (and changes to `whosonfirst/go-whosonfirst-spelunker`).

**Comment by nvkelso** [comment]
Verified, thanks!
